import { readFile, readdir } from "node:fs/promises";
import { existsSync, realpathSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

/**
 * Skill policy checks.
 *
 * These are the rules that are cheaper to enforce mechanically than to review by
 * eye: the shared conventions must not drift between skills, every script must
 * carry the resolver block, and no skill may talk to a provider directly. The
 * integration layer exists so credentials live in exactly one place; a stray
 * `curl` to a provider in a skill script would quietly create a second one.
 *
 * Exported as a function so `scripts/verify.mjs` can fold these into the single
 * gate, and runnable directly so `tools/validate-skills.sh` works standalone.
 */

const MARKER_OPEN = "# >>> agency-lib-resolver";
const MARKER_CLOSE = "# <<< agency-lib-resolver";

/** A script that runs on a client host cannot source this repository's library. */
const STANDALONE_MARKER = "@standalone-remote";

/** Requests to a provider's own API, which must go through the engine instead. */
const PROVIDER_ENDPOINTS = [
  { name: "Cloudflare API", regex: /api\.cloudflare\.com/ },
  { name: "GitHub API", regex: /api\.github\.com/ },
  { name: "Slack API", regex: /(?:slack\.com\/api|hooks\.slack\.com)/ },
];

/** Direct engine invocations that belong in conventions/lib/integration.sh. */
const INLINE_ENGINE_CALLS = [
  { name: "inline `warpmetal integration`", regex: /warpmetal\s+integration\b/ },
  { name: "inline `warpmetal env secret`", regex: /warpmetal\s+env\s+secret\b/ },
];

async function listFiles(directory, predicate, into = []) {
  let entries;
  try {
    entries = await readdir(directory, { withFileTypes: true });
  } catch {
    return into;
  }
  for (const entry of entries) {
    if (entry.name.startsWith(".") || entry.name === "node_modules") continue;
    const path = join(directory, entry.name);
    if (entry.isDirectory()) await listFiles(path, predicate, into);
    else if (entry.isFile() && predicate(entry.name)) into.push(path);
  }
  return into;
}

async function readIfExists(path) {
  try {
    return await readFile(path, "utf8");
  } catch {
    return null;
  }
}

/**
 * The provider names the CLI actually implements, read from the catalog source.
 *
 * The catalog lives in TypeScript, which this Node-only gate cannot import
 * without a build step, so the `PROVIDERS` literal is read directly. The slice is
 * bounded by the array's own delimiters and a zero-result read is a failure, so
 * a refactor that renames the constant cannot turn this check into a no-op.
 */
export async function readProviderCatalog(root) {
  const path = join(root, "packages/warpmetal-cli/src/integration/registry.ts");
  const source = await readIfExists(path);
  if (source === null) {
    return { providers: [], capabilities: [], problem: `missing catalog: ${relative(root, path)}` };
  }
  const start = source.indexOf("PROVIDERS: readonly ProviderSpec[] = [");
  if (start === -1) {
    return { providers: [], capabilities: [], problem: "could not locate the PROVIDERS array" };
  }
  const end = source.indexOf("\n];", start);
  if (end === -1) {
    return { providers: [], capabilities: [], problem: "the PROVIDERS array is not terminated" };
  }
  const block = source.slice(start, end);
  const providers = [...block.matchAll(/^\s{4}name: "([a-z0-9-]+)",$/gm)].map((match) => match[1]);
  const capabilities = [...block.matchAll(/"([a-z]+\.[a-z]+\.[a-z]+)"/g)].map((match) => match[1]);
  if (providers.length === 0) {
    return { providers: [], capabilities: [], problem: "the PROVIDERS array declares no provider" };
  }
  return { providers, capabilities, problem: null };
}

export async function collectSkillPolicyFailures({ root }) {
  const failures = [];
  const skillsRoot = join(root, "skills");

  let skillNames;
  try {
    skillNames = (await readdir(skillsRoot, { withFileTypes: true }))
      .filter((entry) => entry.isDirectory() && !entry.name.startsWith("."))
      .map((entry) => entry.name)
      .sort();
  } catch (error) {
    return [`skills/ is unreadable: ${error.message}`];
  }

  // 1. The shared conventions must be byte-identical in every skill that ships
  //    them, and identical to the canonical `conventions/` at the repository root.
  //    Seven copies exist because a skill directory must work on its own; that is
  //    only safe if the copies cannot drift, so the copies are generated by
  //    `npm run sync:conventions` and any difference is a hand-edit.
  const canonicalDir = join(root, "conventions");
  const canonicalFiles = (await listFiles(canonicalDir, () => true))
    .map((path) => relative(canonicalDir, path).split(sep).join("/"))
    .sort();
  const canonicalContents = new Map();
  for (const file of canonicalFiles) {
    canonicalContents.set(file, await readFile(join(canonicalDir, file), "utf8"));
  }

  for (const name of skillNames) {
    const dir = join(skillsRoot, name, "conventions");
    if (!existsSync(dir)) continue;
    const files = (await listFiles(dir, () => true))
      .map((path) => relative(dir, path).split(sep).join("/"))
      .sort();

    for (const file of canonicalFiles) {
      if (!files.includes(file)) {
        failures.push(`skills/${name}/conventions is missing ${file}; run npm run sync:conventions`);
      }
    }
    for (const file of files) {
      if (!canonicalFiles.includes(file)) {
        failures.push(
          `skills/${name}/conventions/${file} does not exist in the canonical conventions/; run npm run sync:conventions`,
        );
        continue;
      }
      if ((await readFile(join(dir, file), "utf8")) !== canonicalContents.get(file)) {
        failures.push(
          `skills/${name}/conventions/${file} has drifted from conventions/${file}; run npm run sync:conventions`,
        );
      }
    }
  }

  // 2. Every skill script carries the resolver block, the documented contract that
  //    lets a skill directory work standalone. See conventions/client-manifest.md.
  //    The one sanctioned exemption is `@standalone-remote`: a script that is piped
  //    into a client host cannot source anything from the repository, and claiming
  //    otherwise would be a lie the validator should not force.
  for (const skill of skillNames) {
    const scriptDir = join(skillsRoot, skill, "scripts");
    for (const path of await listFiles(scriptDir, (name) => name.endsWith(".sh"))) {
      const text = await readFile(path, "utf8");
      const relativePath = relative(root, path);
      if (text.includes(STANDALONE_MARKER)) continue;
      if (!text.includes(MARKER_OPEN) || !text.includes(MARKER_CLOSE)) {
        failures.push(
          `${relativePath} is missing the agency-lib-resolver marker block (or the @standalone-remote marker)`,
        );
        continue;
      }
      const block = text.slice(text.indexOf(MARKER_OPEN), text.indexOf(MARKER_CLOSE));
      if (!block.includes("AGENCY_LIB")) {
        failures.push(`${relativePath} has a resolver block that does not consult $AGENCY_LIB`);
      }
    }
  }

  // 3. No skill talks to a provider or to the engine directly. The integration
  //    library is the one place allowed to do both, which is the whole point of it.
  for (const skill of skillNames) {
    const skillDir = join(skillsRoot, skill);
    for (const path of await listFiles(skillDir, (name) => name.endsWith(".sh"))) {
      const relativePath = relative(root, path);
      if (relativePath.split(/[\\/]/).includes("lib")) continue;
      const text = await readFile(path, "utf8");
      for (const pattern of PROVIDER_ENDPOINTS) {
        if (pattern.regex.test(text)) {
          failures.push(`${relativePath} calls the ${pattern.name} directly; use conventions/lib/integration.sh`);
        }
      }
      for (const pattern of INLINE_ENGINE_CALLS) {
        if (pattern.regex.test(text)) {
          failures.push(`${relativePath} contains an ${pattern.name}; use conventions/lib/integration.sh`);
        }
      }
    }
  }

  // 4. A declared integration must exist in the catalog. Declaring one the engine
  //    does not implement is worse than declaring none, because an agent would
  //    plan around a capability that is not there.
  const catalog = await readProviderCatalog(root);
  if (catalog.problem !== null) {
    failures.push(`integration catalog is unreadable: ${catalog.problem}`);
  } else {
    for (const skill of skillNames) {
      const metaPath = join(skillsRoot, skill, "skill.json");
      const text = await readIfExists(metaPath);
      if (text === null) continue;
      let meta;
      try {
        meta = JSON.parse(text);
      } catch {
        continue;
      }
      const declared = meta.integrations;
      if (declared === undefined) continue;
      if (!Array.isArray(declared) || declared.some((entry) => typeof entry !== "string")) {
        failures.push(`skills/${skill}/skill.json integrations must be an array of strings`);
        continue;
      }
      for (const provider of declared) {
        if (!catalog.providers.includes(provider)) {
          failures.push(
            `skills/${skill}/skill.json declares integration "${provider}", which is not in the catalog (${catalog.providers.join(", ")})`,
          );
        }
      }
      if (declared.length === 0) {
        failures.push(`skills/${skill}/skill.json integrations is present but empty; remove the field instead`);
      }
    }
  }

  return failures;
}

const invokedDirectly = (() => {
  const entry = process.argv[1];
  if (typeof entry !== "string") return false;
  try {
    return import.meta.url === pathToFileURL(realpathSync(entry)).href;
  } catch {
    return false;
  }
})();

if (invokedDirectly) {
  const root = fileURLToPath(new URL("..", import.meta.url));
  const failures = await collectSkillPolicyFailures({ root });
  if (failures.length > 0) {
    console.error(`validate-skills: ${failures.length} problem(s) found`);
    for (const failure of failures) console.error(`  - ${failure}`);
    process.exit(1);
  }
  console.log("validate-skills: ok");
}
